import { ArrowRight, Layers3, RotateCcw } from 'lucide-react'
import { useState, type CSSProperties } from 'react'
import type { LanguageMode } from '../lib/i18n'
import { copy, type Copy } from '../lib/synthesis'
import { ColorPaletteStudio } from './ColorPaletteStudio'

const techniques: Array<{ title: Copy; purpose: Copy; task: Copy; baseline: Copy; measure: Copy; href: string }> = [
  { title: ['3D + layered evidence', '三维与证据分层'], purpose: ['Separate data, transformation, and interpretation before making a claim. Depth organizes the explanation; it does not encode a measured quantity.', '在提出主张前分开数据、转换与解释。深度组织解释，不编码测量值。'], task: ['Identify which layer contains an observation and which contains an inference.', '辨认哪一层包含观察、哪一层包含推断。'], baseline: ['A flat, labeled stack with the same content.', '具有相同内容的平面标签列表。'], measure: ['Correct layer identification, reading errors, and ease of navigation.', '图层识别正确情况、阅读错误与导航便利性。'], href: '#evidence' },
  { title: ['Animation + time', '动画与时间'], purpose: ['Step through monthly precipitation while keeping the scale, units, and selected month visible. A moving mark is a dated reading, not a traveling storm.', '逐步查看每月降水，保留尺度、单位与选定月份。移动的标记表示带日期读数，不代表移动的风暴。'], task: ['Find the wettest month in a selected year and report its value and units.', '找出所选年份降水最多的月份，报告读数与单位。'], baseline: ['A static annual chart and values table.', '静态年度图表与数值表。'], measure: ['Answer accuracy, time to an answer, and whether users can pause and recover.', '回答准确性、作答时间，以及用户能否暂停和恢复。'], href: '#water' },
  { title: ['Chapter 10 · color', '第 10 章 · 色彩'], purpose: ['Match hue and lightness to categories, magnitudes, or a meaningful midpoint; preserve labels and accessible alternatives.', '将色相与明度匹配类别、数量或有意义的中点，保留标签与无障碍替代方案。'], task: ['Identify a category or compare a value without depending on hue alone.', '识别类别或比较数值，同时不只依赖色相。'], baseline: ['The same marks and labels with a simple, task-matched palette.', '使用简单且适合任务的色板，保持相同标记与标签。'], measure: ['Misreadings in normal and grayscale views; label contrast; interpretation under 3D lighting.', '标准与灰度视图中的误读、标签对比度，以及三维光照下的解释。'], href: '#color-studio' },
]
const layers: Array<{ title: Copy; water: Copy; mountain: Copy }> = [
  { title: ['01 · Source', '01 · 资料'], water: ['OSM geometry + NASA POWER precipitation', 'OSM 几何数据 + NASA POWER 降水'], mountain: ['Paper descriptions / permitted tDAR records', '论文描述 / 获准使用的 tDAR 记录'] },
  { title: ['02 · Transformation', '02 · 转换'], water: ['Map projection + date selection', '地图投影 + 日期选择'], mountain: ['Qualitative transcription / documented aggregation', '定性转录 / 有记录的聚合'] },
  { title: ['03 · Interpretation', '03 · 解释'], water: ['A question to check in Kunshan', '需在昆山检验的问题'], mountain: ['A material pattern to contextualize', '需放回语境的物质模式'] },
]

export function AdvancedStudio({ language, motionEnabled }: { language: LanguageMode; motionEnabled: boolean }) {
  const t = copy(language)
  const [technique, setTechnique] = useState(0)
  const [depth, setDepth] = useState(48)
  const [rotation, setRotation] = useState(-14)
  const [place, setPlace] = useState<'water' | 'mountain'>('water')
  const [dimension, setDimension] = useState<'flat' | '3d'>('3d')
  const current = techniques[technique]
  return <section id="advanced" className="chapter tutorial-chapter advanced-chapter" data-chapter aria-labelledby="advanced-title">
    <div className="advanced-intro" data-no-translate><div className="synthesis-heading"><span className="synthesis-kicker">{t(['Week 6 · advanced techniques + evaluation', '第 6 周 · 进阶技术与评价'])}</span><h2 id="advanced-title">{t(['An advanced effect needs a reason.', '进阶效果需要明确理由。'])}</h2><p>{t(['Keep the question and data fixed. Change one design decision, compare it with a simpler view, and ask whether the task becomes easier. Chapter 10 color is part of this advanced practice.', '固定问题与数据。改变一项设计选择，与更简单的视图比较，检验任务是否更容易完成。第 10 章色彩属于这部分进阶实践。'])}</p></div>
      <div className="advanced-options" role="group" aria-label={t(['Advanced technique', '进阶技术'])}>{techniques.map((item, i) => <button type="button" key={i} aria-pressed={technique === i} onClick={() => setTechnique(i)}>{t(item.title)}</button>)}</div>
      <article className="technique-brief" aria-live="polite"><h3>{t(current.title)}</h3><p>{t(current.purpose)}</p><dl><div><dt>{t(['One user task', '一个用户任务'])}</dt><dd>{t(current.task)}</dd></div><div><dt>{t(['Compare with', '比较基线'])}</dt><dd>{t(current.baseline)}</dd></div><div><dt>{t(['What to evaluate', '评价内容'])}</dt><dd>{t(current.measure)}</dd></div></dl><a href={current.href}>{t(['Try this technique', '尝试这项技术'])}<ArrowRight /></a></article>
      <div className="layer-lab"><div className="layer-lab-controls"><Layers3 aria-hidden="true" /><h3>{t(['Pull the evidence apart.', '拆开证据的层次。'])}</h3><p>{t(['Drag the separation control, switch places, then flatten the view. All three layers keep their meaning.', '拖动分层控件，切换地点，再展平视图。三层内容的含义保持一致。'])}</p><div role="group" aria-label={t(['Evidence case', '证据案例'])}><button type="button" aria-pressed={place === 'water'} onClick={() => setPlace('water')}>{t(['Kunshan', '昆山'])}</button><button type="button" aria-pressed={place === 'mountain'} onClick={() => setPlace('mountain')}>{t(['Mandara', '曼达拉'])}</button></div><div role="group" aria-label={t(['Layer view', '图层视图'])}><button type="button" aria-pressed={dimension === '3d'} onClick={() => setDimension('3d')}>{t(['3D layers', '三维分层'])}</button><button type="button" aria-pressed={dimension === 'flat'} onClick={() => setDimension('flat')}>{t(['Flat baseline', '平面基线'])}</button></div><label>{t(['Layer separation', '图层间距'])}<input type="range" min="0" max="90" value={depth} disabled={dimension === 'flat'} onChange={(e) => setDepth(Number(e.target.value))} /></label><label>{t(['View angle', '观看角度'])}<input type="range" min="-22" max="22" value={rotation} disabled={dimension === 'flat'} onChange={(e) => setRotation(Number(e.target.value))} /></label><button type="button" onClick={() => { setDepth(48); setRotation(-14); setDimension('3d') }}><RotateCcw />{t(['Reset view', '重置视图'])}</button></div><div className={'layer-viewport ' + (dimension === 'flat' ? 'is-flat' : 'is-3d')} style={{ '--layer-turn': rotation + 'deg', '--layer-depth': depth + 'px' } as CSSProperties}><div className="evidence-layer-stack" data-motion={motionEnabled ? 'on' : 'off'}>{layers.map((layer, i) => <article key={i} style={{ '--layer-index': i } as CSSProperties}><span>{t(layer.title)}</span><p>{t(layer[place])}</p></article>)}</div><p>{t(['Explanatory layers; spacing is not data.', '解释性图层；间距不代表数据。'])}</p></div></div>
      <div className="chapter-ten-bridge"><span>CH. 10</span><div><h3>{t(['Map color and other channels', '映射色彩与其他视觉通道'])}</h3><p>{t(['Kunshan rainfall needs ordered magnitude; waterway types and CP identifiers are categories; deviations require a stated reference value. SDG icon colors identify goals and must not become a numeric data scale.', '昆山降水需要表达有序数量；水道类型与 CP 标识属于类别；偏差需要明确参考值。SDG 图标颜色识别目标，不应被用作数值色标。'])}</p><a href="https://www.cs.ubc.ca/~tmm/vadbook/" target="_blank" rel="noreferrer">Munzner, T. (2014). <cite>Visualization analysis and design</cite>, Chapter 10.</a></div></div>
    </div>
    <ColorPaletteStudio />
    <div className="advanced-exit" data-no-translate><h3>{t(['Keep the effect only if it helps.', '保留真正有用的效果。'])}</h3><p>{t(['In your Week 6 pilot, give the same task with and without the effect. Record the answer, errors, access needs, and one revision. Report the small study’s limits; do not claim a universal improvement.', '在第 6 周试点中，针对有无该效果的版本布置同一任务。记录回答、错误、无障碍需求与一项修订。说明小规模研究的限制，不宣称普遍提升。'])}</p><a href="#validate">{t(['Record the evaluation', '记录评价'])}<ArrowRight /></a></div>
  </section>
}
