import { useState } from 'react'
import paper from '../../public/data/mandara-teaching.json'
import type { LanguageMode } from '../lib/i18n'
import { copy, type Copy } from '../lib/synthesis'

const names: Copy[] = [['Western sites', '西部遗址'], ['Eastern sites', '东部遗址'], ['Neolithic signal', '新石器时代信号']]

export function ReportedPatternNetwork({ language }: { language: LanguageMode }) {
  const t = copy(language)
  const [selected, setSelected] = useState(13)
  const [filter, setFilter] = useState<'all' | 'dominant' | 'smaller'>('all')
  const edges = paper.signatures.flatMap((group, gi) => group.values.flatMap((value, ci) => value > 0 ? [{ gi, ci, value }] : []))
    .filter((edge) => filter === 'all' || (filter === 'dominant' ? edge.value === 1 : edge.value === 0.35))
  const selectedEdges = edges.filter((edge) => edge.ci === selected)
  return <section id="network-example" className="reported-network" aria-labelledby="network-title">
    <div className="synthesis-heading"><span className="synthesis-kicker">{t(['Week 3 → Week 5 · networks + linked selection', '第 3 周 → 第 5 周 · 网络与联动选择'])}</span><h3 id="network-title">{t(['Make a relationship inspectable.', '让关系可以被查验。'])}</h3><p>{t(['This bipartite graph connects two types of node: site groups and CP model identifiers. An edge records a qualitative statement in the paper-derived teaching layer. Select a CP to highlight its reported links and read the same relationships in text.', '这个二分图连接两类节点：遗址分组与 CP 模型标识。一条边记录论文衍生教学层中的一项定性陈述。选择 CP，高亮其已报告连边，并在文字中阅读相同关系。'])}</p></div>
    <div className="network-workbench"><div className="network-drawing"><svg viewBox="0 0 440 660" role="group" aria-label={t(['Reported group–CP links. Use the selector for keyboard access.', '已报告的分组–CP 连边。可使用选择框进行键盘操作。'])}>
      <title>{t(['Qualitative group–pattern network', '定性分组–模式网络'])}</title>
      {edges.map((edge) => <path key={edge.gi + '-' + edge.ci} d={'M78,' + (145 + edge.gi * 180) + ' C220,' + (145 + edge.gi * 180) + ' 230,' + (40 + edge.ci * 44) + ' 350,' + (40 + edge.ci * 44)} fill="none" stroke={edge.ci === selected ? '#075c78' : '#c1cdd0'} strokeWidth={edge.ci === selected ? 4 : 1.4} strokeDasharray={edge.value === 0.35 ? '7 5' : undefined} />)}
      {names.map((name, i) => <g key={i}><circle cx="78" cy={145 + i * 180} r="30" fill="#245c70" /><text x="78" y={153 + i * 180} textAnchor="middle" fill="white" fontSize="23">G{i + 1}</text><title>{t(name)}</title></g>)}
      {paper.culture_periods.map((cp, i) => <g key={cp} className="network-cp-node" role="button" tabIndex={0} aria-label={cp} aria-pressed={selected === i} onClick={() => setSelected(i)} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setSelected(i) } }}><rect x="315" y={21 + i * 44} width="81" height="37" rx="6" fill={selected === i ? '#245c70' : '#fff'} stroke="#245c70" strokeWidth={selected === i ? 3 : 1} /><text x="355" y={47 + i * 44} textAnchor="middle" fill={selected === i ? '#fff' : '#20343b'} fontSize="22">{cp}</text></g>)}
    </svg><p>{t(['Solid = dominant reported membership; dashed = smaller reported membership. Layout is fixed by group and CP identifier for stable comparison; positions are not geography.', '实线 = 已报告的主要归属；虚线 = 已报告的较小归属。布局按分组与 CP 标识固定排列，便于稳定比较；位置不表示地理坐标。'])}</p></div>
    <div className="network-reading"><label>{t(['Select a CP', '选择 CP'])}<select value={selected} onChange={(e) => setSelected(Number(e.target.value))}>{paper.culture_periods.map((cp, i) => <option key={cp} value={i}>{cp}</option>)}</select></label><fieldset><legend>{t(['Show reported links', '显示已报告连边'])}</legend><div className="network-filters">{(['all', 'dominant', 'smaller'] as const).map((f, i) => <button key={f} type="button" aria-pressed={filter === f} onClick={() => setFilter(f)}>{t(([['All reported', '全部已报告'], ['Dominant', '主要'], ['Smaller', '较小']] as Copy[])[i])}</button>)}</div></fieldset><div aria-live="polite"><h4>{paper.culture_periods[selected]} · {selectedEdges.length} {t(['visible links', '条可见连边'])}</h4><ul>{selectedEdges.map((edge) => <li key={edge.gi}><strong>G{edge.gi + 1} · {t(names[edge.gi])}</strong><span>{paper.signatures[edge.gi].sites}</span><p>{t(edge.value === 1 ? ['Dominant reported membership', '已报告的主要归属'] : ['Smaller reported membership', '已报告的较小归属'])}</p></li>)}</ul>{selectedEdges.length === 0 && <p>{t(['No reported link in this filter. This does not establish absence in the archaeological record.', '当前筛选下没有已报告连边；这不等于考古记录中不存在。'])}</p>}</div><details><summary>{t(['Nodes, edges, and algorithm', '节点、连边与算法'])}</summary><p>{t(['G1 = Western sites; G2 = Eastern sites; G3 = Neolithic signal. Read each signature row; add a link only for a positive qualitative assertion (1 or 0.35). Keep the assertion type as a label, not a numeric weight. Filter edges, then coordinate the graph highlight and the textual list through one selected CP.', 'G1 = 西部遗址；G2 = 东部遗址；G3 = 新石器时代信号。读取各纹饰特征行，仅为正的定性陈述（1 或 0.35）添加连边。保留陈述类型标签，不把数值视为权重。筛选连边后，使用同一选定 CP 协调图形高亮与文字列表。'])}</p></details><p className="network-boundary">{t(['Edges represent reported group–pattern associations, not social ties, travel, chronology, or cultural identity. An omitted link means no assertion in this teaching layer. The values are not counts or probabilities.', '连边表示已报告的分组–模式关联，不表示社会关系、旅行、年代或文化身份。省略连边表示教学层中没有该陈述；数值并非计数或概率。'])}</p><a href="https://doi.org/10.48550/arXiv.1511.05185" target="_blank" rel="noreferrer">O’Brien, J. D., Lin, K., &amp; MacEachern, S. (2015). <cite>Mixture model of pottery distributions from Lake Chad Basin archaeological sites reveals ancient segregation patterns</cite>.</a><a href="#mountain">{t(['Compare with the matrix and CP guide', '与矩阵和 CP 指南比较'])}</a></div></div>
  </section>
}
